### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by chuckwondo** [nasa/python_cmr#36]
Arguably, type annotations are extremely helpful and have become quite common, either directly within Python libraries, or within type stub packages (such as those available on [typeshed](https://github.com/python/typeshed)).

Since typing was introduced in Python 3.5 (IIRC), adding type annotations should likely be done after #35 is implemented, so that it is clear that this library supports only versions of Python no older than 3.5 (although likely no older than 3.8, as 3.8 is even close to "retirement").

The motivation here is not only as part of "modernizing" this library, but also because the lack of type annotations here has led to defining type stubs for this library within the earthaccess library, which uses this library. See https://github.com/nsidc/earthaccess/issues/508. I would like to use those type stubs as a basis for implementing a solution to this issue.

**Comment by frankinspace** [comment]
Yes, big supporter of type annotations
