### ISSUE TITLE
Collecting changes for release 0.11.0

### ISSUE THREAD

**Issue by frankinspace** [nasa/python_cmr#45]
Using this issue as a collection point for stakeholders to decide when we should release the next version of python_cmr. 

If you are listed as an assignee (or pinged directly @chuckwondo ), I'd like to have your concurrence that:

1) The changes below constitute a [minor](https://semver.org/#spec-item-7) release (meaning the next release will be 0.11.0)
2) Yes/No should a release be created with just these changes. Yes: release can continue, No: we should wait for some additional feature/issue before creating a release
3) You are willing to verify the release prior to merging to `main`

If you think there should be more stakeholders in this discussion, please add them to the list of assignees.

Currently, we have the following changes pending for the next release:

### Changed

- [issues/35](https://github.com/nasa/python_cmr/issues/35) Eliminated
  accommodation for Python versions older than 3.8 and updated CI build to test
  against Python versions 3.8 through 3.12.  Also, fixed all flake8 warnings.

### Added

- [issues/36](https://github.com/nasa/python_cmr/issues/36) Added type annotations.

## Fixed

- [issues/42](https://github.com/nasa/python_cmr/issues/42) Fixed bug where a
  `KeyError` was thrown from `Query.get` when the query format was a supported
  format other than `"json"`.  Further, in such cases, too many items would be
  fetched from the CMR due to a bug in how items were counted.  Now, no more
  than `limit` items are fetched.

**Comment by briannapagan** [comment]
I suggest we move forward with 0.11.0 release with these three listed changes.

**Comment by chuckwondo** [comment]
@frankinspace, do you need anything else for this release?
