### ISSUE TITLE
Add vcrpy cassettes for revision_date unit tests

### ISSUE THREAD

**Issue by chuckwondo** [nasa/python_cmr#70]
New unit tests recently added for testing new `revision_date` search functionality are missing vcrpy cassettes to prevent unit tests from making live requests. This can lead to broken tests in the future, should the responses change.

Specifically, these tests need to be supported by vcrpy cassettes:

- `test_revision_date` in `tests/test_collection.py`
- `test_revision_date` in `tests/test_granule.py`

**Comment by frankinspace** [comment]
@chuckwondo it doesn't like any of the test functions in `tests/test_collection.py` or `tests/test_granule.py` are using vcrpy as far as I can tell? We should add it for all these tests in that case.

**Comment by chuckwondo** [comment]
> @chuckwondo it doesn't like any of the test functions in `tests/test_collection.py` or `tests/test_granule.py` are using vcrpy as far as I can tell? We should add it for all these tests in that case.

Correct. We haven't needed to use it in those files yet, as none of the tests make any http requests. Only the new tests for revision date actually make http requests. The rest of the tests simply construct query instances without actually executing the queries.
