### ISSUE TITLE
Support multiple-point searches in queries

### ISSUE THREAD

**Issue by Sherwin-14** [nasa/python_cmr#72]
The current point function support's a single point only. Would be nice to have support for multiple points

**Comment by chuckwondo** [comment]
For reference:

- [Search for collections by point(s)](https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#c-point)
- [Search for granules by point(s)](https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#g-point). Note that the example shows only 1 point, but per [finding granules by spatial](https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#g-spatial):

  > The parameters used for searching granules by spatial are the same as the spatial parameters used in collections searches. (See under "Find collections by Spatial" for more details.)

**Comment by chuckwondo** [comment]
Fixed by #73
