### ISSUE TITLE
Discussion on next release

### ISSUE THREAD

**Issue by frankinspace** [nasa/python_cmr#84]
There are a number of changes that have been completed:

https://github.com/nasa/python_cmr/blob/develop/CHANGELOG.md#unreleased

Suggestion is to create a release containing all of these changes. I think it makes sense for the next release to be a minor release as 0.13.0.

@nasa/python_cmr any objections?

**Comment by chuckwondo** [comment]
Works for me! Perhaps just tweak the very minor markdown issue at the end of the last item in the unreleased list in the changelog.

**Comment by frankinspace** [comment]
@chuckwondo @briannapagan FYI I started a release wiki page to outline the steps necessary to publish a new release https://github.com/nasa/python_cmr/wiki/Release-Process. Please review it when you get a chance. I'd like to have one of you run the release process next time if possible

**Comment by chuckwondo** [comment]
> @chuckwondo @briannapagan FYI I started a release wiki page to outline the steps necessary to publish a new release https://github.com/nasa/python_cmr/wiki/Release-Process. Please review it when you get a chance. I'd like to have one of you run the release process next time if possible

Great!

In the section "Step 2: Prepare release branch" should the first step (prior to the current first step) be "Pull the latest revision from the `develop` branch"?

**Comment by frankinspace** [comment]
@chuckwondo updated

**Comment by chuckwondo** [comment]
The release process looks good. Next time, when either @briannapagan or I run through the process, we can make further adjustments to the doc, if we find anything else requiring clarification. Thanks again!
